# Generated by Django 4.1.4 on 2022-12-21 06:58

from django.db import migrations, models
import rest_ms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.IntegerField()),
                ('order', rest_ms.models.ListField()),
                ('total', models.IntegerField()),
                ('feedback', models.CharField(max_length=20)),
                ('feedback_comments', models.TextField()),
            ],
        ),
    ]
