# Generated by Django 4.1.4 on 2022-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
