# Generated by Django 4.1.4 on 2022-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_ms', '0002_alter_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.FloatField(),
        ),
    ]
